In [3]:
# Exercise 1: Create two dimensional 3*3 array and perform ndim, shape, slicing operation on it.

In [5]:
import numpy as np

# Create a two-dimensional 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

print("Original 3x3 array:")
print(arr)

Original 3x3 array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
# Perform ndim operation (number of dimensions)
num_dimensions = arr.ndim
print(f"\nNumber of dimensions (ndim): {num_dimensions}")


Number of dimensions (ndim): 2


In [7]:
# Perform shape operation (dimensions of the array)
array_shape = arr.shape
print(f"Shape of the array: {array_shape}")

Shape of the array: (3, 3)


In [8]:
# Perform slicing operations

# Slice 1: Get the first row
slice_row_1 = arr[0, :]
print(f"\nSlice 1 (first row): {slice_row_1}")


Slice 1 (first row): [1 2 3]


In [9]:
# Slice 2: Get the last column
slice_col_last = arr[:, 2]
print(f"Slice 2 (last column): {slice_col_last}")

Slice 2 (last column): [3 6 9]


In [10]:
# Slice 3: Get the element at row 1, column 1 (indexing starts from 0)
slice_element = arr[1, 1]
print(f"Slice 3 (element at [1,1]): {slice_element}")


Slice 3 (element at [1,1]): 5


In [11]:
# Slice 4: Get a sub-array (e.g., the top-left 2x2 sub-array)
slice_sub_array = arr[0:2, 0:2]
print(f"Slice 4 (top-left 2x2 sub-array):")
print(slice_sub_array)

Slice 4 (top-left 2x2 sub-array):
[[1 2]
 [4 5]]


In [ ]:
#  Exercise 2 :  Create one dimensional array and perform ndim,shape, reshape  operation on it.

In [12]:
# 1. Create a one-dimensional array
one_d_array = np.array([1, 2, 3, 4, 5, 6])
print(f"Original 1D array: {one_d_array}")

Original 1D array: [1 2 3 4 5 6]


In [13]:
# 2. Perform ndim operation (number of dimensions)
num_dimensions = one_d_array.ndim
print(f"Number of dimensions (ndim): {num_dimensions}")

Number of dimensions (ndim): 1


In [14]:
# 3. Perform shape operation (shape of the array)
array_shape = one_d_array.shape
print(f"Shape of the array: {array_shape}")

Shape of the array: (6,)


In [15]:
# 4. Perform reshape operation (e.g., reshape to a 2D array)
# The product of the new dimensions must equal the total number of elements in the original array.
reshaped_array = one_d_array.reshape(2, 3) # Reshape to a 2x3 matrix
print(f"Reshaped array (2x3): {reshaped_array}")


Reshaped array (2x3): [[1 2 3]
 [4 5 6]]


In [16]:
another_reshaped_array = one_d_array.reshape(3, 2)
print(f"Another reshaped array (3x2): {another_reshaped_array}")

Another reshaped array (3x2): [[1 2]
 [3 4]
 [5 6]]
